# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/GitHub/viVado_Projects/Bike/Bike.runs/synth_1/TB_BIKE.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache C:/Users/20115/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-4748-AbdelazizPC/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/GitHub/viVado_Projects/Bike/Bike.cache/wt [current_project]
set_property parent.project_path E:/GitHub/viVado_Projects/Bike/Bike.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.1 [current_project]
set_property ip_output_repo e:/GitHub/viVado_Projects/Bike/Bike.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files {{e:/GitHub/Prevasive_Internship/Bike_Implementation/BIKE-main/HDL/KeyGeneration/Level 1/B32S1/tv/ROM_DATA/pk.coe}}
add_files {{e:/GitHub/Prevasive_Internship/Bike_Implementation/BIKE-main/HDL/KeyGeneration/Level 1/B32S1/tv/ROM_DATA/sk0.coe}}
add_files {{e:/GitHub/Prevasive_Internship/Bike_Implementation/BIKE-main/HDL/KeyGeneration/Level 1/B32S1/tv/ROM_DATA/sk1.coe}}
add_files {{e:/GitHub/Prevasive_Internship/Bike_Implementation/BIKE-main/HDL/KeyGeneration/Level 1/B32S1/tv/ROM_DATA/sigma.coe}}
add_files -quiet E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_pk/blk_mem_gen_pk.dcp
set_property used_in_implementation false [get_files E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_pk/blk_mem_gen_pk.dcp]
read_mem {
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sk1/blk_mem_gen_sk1.mif
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sigma/blk_mem_gen_sigma.mif
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sk0/blk_mem_gen_sk0.mif
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_pk/blk_mem_gen_pk.mif
}
read_verilog -library xil_defaultlib E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sk1/simulation/blk_mem_gen_v8_4.v
read_vhdl -library xil_defaultlib {
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_settings.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/RegisterFDRE.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_counter_inc_stop.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_sampler.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_bram_dual_port.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_generic_bram_shared.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_generic_bram.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_BRAM.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_inversion_bram_assignment.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_inversion_fsm_bram.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_counter_inc_init.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_squaring_k1_generic.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_counter_inc.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_multiplier.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_BRAM_single_port.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_inversion.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE_sampler_uniform.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/BIKE.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_pk/synth/blk_mem_gen_pk.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/synth/blk_mem_gen_pk.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_pk/blk_mem_gen_pk_stub.vhdl
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/synth/blk_mem_gen_sk0.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sk0/blk_mem_gen_sk0_stub.vhdl
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sk1/synth/blk_mem_gen_sk1.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sk1/blk_mem_gen_sk1_stub.vhdl
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sigma/synth/blk_mem_gen_sigma.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/ip/blk_mem_gen_sigma/blk_mem_gen_sigma_stub.vhdl
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/Bike_Implementation/mohab_led.vhd
  E:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/imports/B32S1/TB_BIKE.vhd
}
read_ip -quiet e:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/ip/blk_mem_gen_sk0/blk_mem_gen_sk0.xci
set_property used_in_implementation false [get_files -all e:/GitHub/viVado_Projects/Bike/Bike.gen/sources_1/ip/blk_mem_gen_sk0/blk_mem_gen_sk0_ooc.xdc]

read_ip -quiet e:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/ip/blk_mem_gen_sk1/blk_mem_gen_sk1.xci
set_property used_in_implementation false [get_files -all e:/GitHub/viVado_Projects/Bike/Bike.gen/sources_1/ip/blk_mem_gen_sk1/blk_mem_gen_sk1_ooc.xdc]

read_ip -quiet e:/GitHub/viVado_Projects/Bike/Bike.srcs/sources_1/ip/blk_mem_gen_sigma/blk_mem_gen_sigma.xci
set_property used_in_implementation false [get_files -all e:/GitHub/viVado_Projects/Bike/Bike.gen/sources_1/ip/blk_mem_gen_sigma/blk_mem_gen_sigma_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/GitHub/viVado_Projects/Bike/Bike.srcs/constrs_1/imports/digilent-xdc-master/Arty-Z7-20-Master.xdc
set_property used_in_implementation false [get_files E:/GitHub/viVado_Projects/Bike/Bike.srcs/constrs_1/imports/digilent-xdc-master/Arty-Z7-20-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/GitHub/viVado_Projects/Bike/Bike.srcs/utils_1/imports/synth_1/TB_BIKE.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top TB_BIKE -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef TB_BIKE.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file TB_BIKE_utilization_synth.rpt -pb TB_BIKE_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
