# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrains.xdc

# Block Designs: bd/artyZ7_bd/artyZ7_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyZ7_bd || ORIG_REF_NAME==artyZ7_bd} -quiet] -quiet

# IP: bd/artyZ7_bd/ip/artyZ7_bd_processing_system7_0_0/artyZ7_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyZ7_bd_processing_system7_0_0 || ORIG_REF_NAME==artyZ7_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==artyZ7_bd_clk_wiz_0_0 || ORIG_REF_NAME==artyZ7_bd_clk_wiz_0_0} -quiet] -quiet

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/artyZ7_bd_ooc.xdc
