# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.srcs/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0.xci
# IP: The module: 'artyZ7_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyZ7_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyZ7_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyZ7_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.srcs/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0.xci
# IP: The module: 'artyZ7_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyZ7_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyZ7_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/GitHub/viVado_Projects/Youtube_Tutorial1/Youtube_Tutorial1.gen/sources_1/bd/artyZ7_bd/ip/artyZ7_bd_clk_wiz_0_0/artyZ7_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'artyZ7_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
